dist: trusty
script: "/bin/true"
notifications:
  email: false
  slack:
    rooms:
      secure: hUYY+W3xazkoAbcblU2iIc2Emx8cq3TxhrsOarV1qoeylG34q9Na8IzJzeJa4uVOz5/U9Zl+30xst4oO/Zow1QZDhUp0+g3OX9shc+FhLPqTgJ8BkGcXZ9/B37UbmrIlgHVcUzGzx34AqT+qML3/kwqhBVOAAcS4B0h+W153fq4C4Uelffug2AYGM0PfzlE19FYgHrjpx4RKJ/1Eozu9YW4mMtspP1soOhz0gmiv2v3IbMN8VYQmlzRu65chEV5eFyn9t4olC27ZcSCAHUjxuMf5EwhO1EsbkdcZTo9FmiiRmTGnpvy2mZtWU93YFfX4NuIlBb45zdqHcUuypiF99NMnBSxcxRVwLRT6xAJlbbDv7Bxgh6e8K+pACEqPCaZ1515j8nEl6//rC8yC9lDsyW+LKxz37S8Q+reCcBrZ9xWMIr9CeMrZU0vzo4pPKhiqFEX5OdY/o8OH1eljU+WiMeKjveDmF84xOiZcyRiHRk/BVQ2Y+BrXVH3V0qGxcdDahMEysRMVJLHouf0pofY6zoP/4AhtM8NWR4pu2RcJ/0J7CKtTtmKJo5nTPR38aAsauI5XJ7rFndBF0sWOCOubN7UG88hPb9MGsMPslrKNGANO2qo8jLuCR9mGZi4Y84KIRX7cSD/C6ChqqiXs3ot1dw1kyoWtIkk0A0zAI53/HOI=
